# Generated by Django 4.2.6 on 2023-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('primary_colors', models.TextField()),
                ('secondary_colors', models.TextField()),
                ('font_family', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
