# Generated by Django 4.2.6 on 2023-10-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand_APi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='font_family',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='primary_colors',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='secondary_colors',
            field=models.TextField(max_length=200),
        ),
    ]
